name: flutter_frontres
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logi.png
  - assets/images/log.png
  - assets/images/reg.png
  - assets/images/regi.png
  - assets/images/logo.png
  - assets/images/profile.jpg
  - assets/images/welcome.gif
